In [16]:
import numpy as np

a=[5,2,3]
b=np.tile(a,[2,1])
print(b)

[[5 2 3]
 [5 2 3]]


In [24]:
c=np.tile([2,3,5],[2,1])
d=b-c
e=np.sum(d**2,axis=0)
e

array([18,  2,  8])

In [36]:
np.sort(e)

array([ 2,  8, 18])